version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.4.0
  aws-ecs: circleci/aws-ecs@0.0.11
  maven: circleci/maven@0.0.4

jobs:
  build_and_deploy:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup common environment variables
          command: |
            echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:latest"' >> $BASH_ENV
            # COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            # IMAGE_TAG=${COMMIT_HASH:=latest}
      # - run:
      #     name: Install dependencies for project
      #     command: gradle assemble
      - run:
          name: Install dependencies for AWS
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
            sudo apt-get install python3-pip
            sudo pip3 install --upgrade awscli
      - run:
          name: Build image
          command: |
            # docker build -t $FULL_IMAGE_NAME .
            docker build -t sample-springboot-eks-image:latest .
            docker tag sample-springboot-eks-image:latest 205477628494.dkr.ecr.ap-south-1.amazonaws.com/springboot-ghactions-repo:latest
      - run:
          name: Push image
          command: |
            # eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            docker login -u AWS -p $(aws ecr get-login-password --region ap-south-1) 205477628494.dkr.ecr.ap-south-1.amazonaws.com
            docker push 205477628494.dkr.ecr.ap-south-1.amazonaws.com/springboot-ghactions-repo:latest
            # docker push $FULL_IMAGE_NAME
workflows:
  build-deploy-qa:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: main